### ISSUE TITLE
Retest scripts

### ISSUE THREAD

**Issue by RichardWarburton** [RichardWarburton/honest-profiler#122]
@neomatrix369 reported that he was getting the following errors when running scripts:

```
readlink: illegal option -- f
usage: readlink [-n] [file …]
```

**Comment by FauxFaux** [comment]
Since 3a7c62c2a25b2461f7681ce1b542af02e906ac52, the scripts are pretty broken on Debian/Ubuntu.

Their "alternatives" system means there's multiple layers of symlinks in front of `javac`:

```
% readlink $(which javac)
/etc/alternatives/javac
% readlink -f $(which javac)     
/usr/lib/jvm/java-8-oracle/bin/javac
```

This is what the `readlink -f` was resolving.

Additionally, the refactor broke the `sed` expression by moving the concatenation before the edit:

`java_home=$(echo ${java_path}../ | sed 's/javac$//'`.

**Comment by cinquin** [comment]
I didn't realize my commit broke things under Linux, but please note that we're now just back to a state where things are broken under OS X instead (as pointed out in issue #207).
