### ISSUE TITLE
tag samples by thread state

### ISSUE THREAD

**Issue by ceeaspb** [RichardWarburton/honest-profiler#41]
to be able to filter/report flat and tree profiles by one or more thread states.

this would be useful if you are looking for cpu consumers and don't want to see any samples that are waiting.

would be interested to see if we can distinguish between code like epoll that java will report as runnable but is waiting not consuming cpu.

**Comment by nitsanw** [comment]
HP only samples interrupted, on CPU threads. Therefore and sleeping threads (waiting/blocked/parked) are completely invisible to it. I think this bug may be invalid.

**Comment by ceeaspb** [comment]
thanks @nitsanw ! yep sounds reasonable.
In the extreme, because the thread could get interrupted at any point, it should be possible to get a stack and thread state where it says it's blocked but the thread was still on cpu in jvm, c or kernel code before it went off cpu. I haven't checked whether that's actually possible, just theorising.
Either way it's probably not of interest so closing 2 years on as you have made a good point. 

I have added some comments in #97 and #124 which were provoked when thinking/reading about this.

**Comment by nitsanw** [comment]
@ceeaspb you are right that it is possible to catch the CPU in the short distance between setting the thread state and actually suspending. This is unlikely to show up in a profiler, but if it does it suggests high contention, or rapid sleep cycles rather than blocked threads. I.e. the issue would be that threads are **being** suspended, rather than that they **are** suspended.
